main_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # 'BASIC' PAGES
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('projects/', views.projects, name='projects'),
    path('about/', views.about, name='about'),
    path('', include('users.urls')),


    # TEST ERROR PAGES
    path('400/', views.error_400, name='400'),
    path('403/', views.error_403, name='403'),
    path('404/', views.error_404, name='404'),
    path('500/', views.error_500, name='500'),


    # TESTER PAGES
    path('tester1/', views.tester1, name='tester1'),
    # path('tester2/', views.tester2, name='tester2'),


    # INCLUDING APP URLS
    path('', include('broken_link_checker.urls')),
    path('', include('quizlet_study_tool.urls')),
    path('', include('event_management.urls')),
    path('', include('site_down.urls')),


    # RESET PASSWORD - names must be exact
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

# Overwrites the default error pages
handler400 = 'main_project.views.error_400'
handler403 = 'main_project.views.error_403'
handler404 = 'main_project.views.error_404'
handler500 = 'main_project.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_down/urls.py
from django.urls import path
from .views import (
	CheckerCreateView, CheckerDetailView, CheckerListView, CheckerUpdateView, CheckerDeleteView
)

app_name = 'site_down'
urlpatterns = [
	# EVENTS
	path('checkers/', CheckerListView.as_view(), name='checker-list'),
	path('checkers/new/', CheckerCreateView.as_view(), name='checker-create'),
	path('checkers/<int:pk>/', CheckerDetailView.as_view(), name='checker-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('checkers/<int:pk>/update/', CheckerUpdateView.as_view(), name='checker-update'),
	path('checkers/<int:pk>/delete/', CheckerDeleteView.as_view(), name='checker-delete'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'
urlpatterns = [
	path('register/', user_views.register, name='users-register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
	path('profile/', user_views.profile, name='users-profile'),
]

site_down/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from uuid import uuid4

# Choices
CHOICES = (
	('Hourly', 'HOURLY'),
	('Daily', 'DAILY'),
	('Weekly', 'WEEKLY'),
)
# ADMIN = User.objects.filter(is_superuser=True, username='brickspy').first().pk


class Checker(models.Model):
	# Site name
	name = models.CharField(max_length=50, blank=True, null=True)
	site = models.URLField(max_length=200, blank=False, null=False)
	scan = models.CharField(max_length=6, blank=False, null=False, choices=CHOICES)
	email = models.EmailField(blank=True, null=True)
	date_created = models.DateTimeField(default=timezone.now)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
	notes = models.TextField(max_length=200, null=True, blank=True, default='')

	def __str__(self):
		return self.site

	def date_published(self):
		return self.date_created.strftime('%m/%d/%Y')

	def get_absolute_url(self):
		return reverse('site_down:checker-detail', kwargs={'pk': self.pk})

	class Meta:
		verbose_name = 'Site'
		verbose_name_plural = "Sites"

site_down/forms.py
from django import forms
from .models import Checker


class BrokenLinkCheckerModelForm(forms.ModelForm):
	class Meta:
		model = Checker
		fields = ['site']
		widgets = {
			'site': forms.URLInput(
				attrs={
					'placeholder': 'http://example.com',
					'class': 'form-control',
				})
		}

site_down/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, DeleteView, UpdateView, CreateView, TemplateView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, send_mass_mail
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site

from .models import Checker


class CheckerListView(LoginRequiredMixin, ListView):
	model = Checker
	template_name = 'site_down/checker_list.html'
	context_object_name = 'checkers'
	ordering = ['-date_created']

	def get_queryset(self):
		return Checker.objects.filter(user=self.request.user)


class CheckerDetailView(LoginRequiredMixin, DetailView):
	model = Checker
	template_name = 'site_down/checker_detail.html'
	context_object_name = 'checker'


# Create your views here.
class CheckerCreateView(LoginRequiredMixin, CreateView):
	model = Checker
	template_name = 'site_down/checker_create.html'
	fields = ['name', 'site', 'scan']
	context_object_name = 'checker'


class CheckerUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Checker
	template_name = 'site_down/checker_update.html'
	fields = ['name', 'site', 'scan']
	context_object_name = 'checker'

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

	def test_func(self):
		checker = self.get_object()
		return self.request.user == checker.user


class CheckerDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Checker
	template_name = 'site_down/checker_delete.html'

	def get_success_url(self):
		return reverse('site_down:checker-list')

	def test_func(self):
		checker = self.get_object()
		return self.request.user == checker.user


def send_email(request):
	checker = Checker.objects.filter(user=request.user).first()
	subject = f'{request.user}, testing site down'
	message = f'Is this your name: {request.user}, testing site down app.'
	from_email = settings.EMAIL_HOST_USER
	recipient_list = [checker.email]
	auth_user = settings.EMAIL_HOST_USER
	auth_password = settings.EMAIL_HOST_PASSWORD
	send_mail(
		subject=subject, message=message, from_email=from_email, recipient_list=recipient_list,
		fail_silently=False, auth_user=auth_user, auth_password=auth_password,
	)

	context = {
		'site': checker.site,
		'email': checker.email
	}

	return render(request=request, template_name='site_down/send_email.html', context=context)

site_down/templates/site_down/checker_create.html
<!--EXTENDS FROM BASE-->
{% extends "base.html" %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Create Checker</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Label-->
            <h1>Create a checker</h1>
            <hr class="red-line">

            <!--The form-->
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <!--Submit-->
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Create</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

site_down/templates/site_down/checker_delete.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Delete Checker</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Label-->
            <h1>Delete the checker</h1>
            <hr class="red-line">

            <!--Form-->
            <form method="POST">
                {% csrf_token %}
                <h3>Confirm "{{ checker.name }}" deletion</h3>
                <br>

                <!--Delete, cancel buttons-->
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Delete</button>
                    <a class="btn btn-outline-secondary" href="{% url 'site_down:checker-detail' checker.pk %}">Cancel</a>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

site_down/templates/site_down/checker_detail.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS STATIC FILES-->
{% load static %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Your Checker</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Event details-->
            <h1>Checker: {{ checker }}</h1>
            <h6>Date created: {{ checker.date_created }}</h6>
            <p>Checker description: {{ checker.description }}</p>
            <br>

            <!--Delete, update event-->
            <div>
                <a class="btn btn-outline-danger" href="{% url 'site_down:checker-delete' checker.pk %}">Delete Checker</a>
                <a class="btn btn-outline-success" href="{% url 'site_down:checker-update' checker.pk %}">Update Checker</a>
            </div>

            <br>

            <!--Events-->
            <h5>Back to checker list</h5>
            <a class="btn btn-primary" href="{% url 'site_down:checker-list' %}">All Checkers</a>

        </div>
    </div>
</div>

{% endblock %}

site_down/templates/site_down/checker_list.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Your Checkers</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Are there any checkers?-->
            {% if not checkers %}
                <h1>You have not created any checkers.</h1>
                <br>
            {% endif %}

            <!--Text-->
            {% if checkers %}
                <h1>These are all of your checkers</h1>
                <br>
            {% endif %}

            <!--Create an checker-->
            <a class="btn btn-primary" href="{% url 'site_down:checker-create' %}">Create a checker</a>
            <br>
            <br>

            <!--Checker list-->
            {% for checker in checkers %}
                <h5><a href="{% url 'site_down:checker-detail' checker.pk %}">{{ checker.name }}</a></h5>
                <br>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

site_down/templates/site_down/checker_update.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Update Checker</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Label-->
            <h1>Update the checker</h1>
            <hr class="red-line">

            <!--Form-->
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}

                <!--Submit-->
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

site_down/templates/site_down/send_email.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Email Sent</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Tells them email sent-->
            <h1>Email sent</h1>

            <h3>Site: {{ site }}</h3>
            <h3>Email: {{ email }}</h3>

        </div>
    </div>
</div>


{% endblock %}