event_management/urls.py
from django.urls import path
from .views import (
	EventDetailView, EventListView, EventCreateView, EventUpdateView, EventDeleteView,
	GuestListView, GuestCreateView, GuestUpdateView, GuestDetailView, GuestDeleteView,
	SendEmail, VerifyAttendance, success
)

app_name = 'event_management'
urlpatterns = [
	# EVENTS
	path('<username>/events/', EventListView.as_view(), name='event_management-events'),
	path('<username>/events/new/', EventCreateView.as_view(), name='event_management-create'),
	path('<username>/events/<int:pk>/', EventDetailView.as_view(), name='event_management-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('<username>/events/<int:pk>/update/', EventUpdateView.as_view(), name='event_management-update'),
	path('<username>/events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_management-delete'),

	# GUESTS
	path('<username>/<int:event_pk>/guests/', GuestListView.as_view(), name='guests'),
	path('<username>/<int:event_pk>/guests/new/', GuestCreateView.as_view(), name='guest-create'),
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/', GuestDetailView.as_view(), name='guest-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/update/', GuestUpdateView.as_view(), name='guest-update'),
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/delete/', GuestDeleteView.as_view(), name='guest-delete'),

	# OTHER FUNCTIONALITY
	path('<username>/<int:event_pk>/guests/send-email', SendEmail.as_view(), name='guest-email'),
	path('event-verification/<int:guest_pk>/<str:token>/', VerifyAttendance.as_view(), name='guest-verify'),
	path('event-verification-success/<int:guest_pk>/', success, name='guest-verify-success'),

]

main_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # 'BASIC' PAGES
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('projects/', views.projects, name='projects'),
    path('about/', views.about, name='about'),
    path('', include('users.urls')),


    # TEST ERROR PAGES
    path('400/', views.error_400, name='400'),
    path('403/', views.error_403, name='403'),
    path('404/', views.error_404, name='404'),
    path('500/', views.error_500, name='500'),


    # TESTER PAGES
    path('tester1/', views.tester1, name='tester1'),
    # path('tester2/', views.tester2, name='tester2'),


    # INCLUDING APP URLS
    path('', include('broken_link_checker.urls')),
    path('', include('quizlet_study_tool.urls')),
    path('', include('event_management.urls')),
    path('', include('site_down.urls')),


    # RESET PASSWORD - names must be exact
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

# Overwrites the default error pages
handler400 = 'main_project.views.error_400'
handler403 = 'main_project.views.error_403'
handler404 = 'main_project.views.error_404'
handler500 = 'main_project.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'
urlpatterns = [
	path('register/', user_views.register, name='users-register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
	path('profile/', user_views.profile, name='users-profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pictures')

    def __str__(self):
        return self.user

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #
    #     img = Image.open(self.image.path)
    #
    #     # This resizes the image if it's bigger than 700x700
    #     # You can also delete the previous image when the user successfully
    #     # changes their profile image
    #     if img.height > 700 or img.width > 700:
    #         output_size = (700, 700)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)
    #

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
# from django import forms
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm
#
# from .models import Profile
#
#
# class UserRegisterForm(UserCreationForm):
# 	# Adding additional fields
# 	email = forms.EmailField(required=False)
# 	User._meta.get_field('email')._unique = True
#
# 	class Meta:
# 		# Whenever the form validates it creates a new user
# 		model = User
# 		fields = ['username', 'email', 'password1', 'password2']
#
#
# # To update username and email
# class UserUpdateForm(forms.ModelForm):
# 	# Adding additional fields
# 	email = forms.EmailField(required=False)
# 	User._meta.get_field('email')._unique = True
#
# 	class Meta:
# 		# Whenever the form validates it creates a new user
# 		model = User
# 		fields = ['username', 'email']
#
#
# # To update the image
# class ProfileUpdateForm(forms.ModelForm):
# 	class Meta:
# 		model = Profile
# 		fields = ['image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('users:users-login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:users-profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)


# from django.shortcuts import render, redirect
# from django.contrib.auth.decorators import login_required
# from django.contrib import messages
#
# from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
#
#
# def register(request):
# 	template_name = 'users/register.html'
# 	if request.method == 'POST':
# 		form = UserRegisterForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			username = form.cleaned_data.get('username')
# 			return redirect('users:users-login')
# 	else:
# 		form = UserRegisterForm()
#
# 	context = {
# 		'form': form
# 	}
# 	return render(request, template_name, context)
#
#
# # Different when using CBV
# @login_required
# @login_required
# def profile(request):
# 	if request.method == 'POST':
# 		u_form = UserUpdateForm(request.POST, instance=request.user)
# 		p_form = ProfileUpdateForm(request.POST,
# 								   request.FILES,
# 								   instance=request.user.profile)
# 		if u_form.is_valid() and p_form.is_valid():
# 			u_form.save()
# 			p_form.save()
# 			messages.success(request, f'Your account has been updated!')
# 			return redirect('users:users-profile')
#
# 	else:
# 		u_form = UserUpdateForm(instance=request.user)
# 		p_form = ProfileUpdateForm(instance=request.user.profile)
#
# 	context = {
# 		'u_form': u_form,
# 		'p_form': p_form
# 	}
#
# 	return render(request, 'users/profile.html', context)

users/templates/users/login.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Login</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <h1>Login</h1>
            <hr class="red-line">

            <!--Form-->
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <!--Submit button-->
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Login</button>
                </div>
                <!--Password reset-->
                <div class="form-group">
                    <small class="text-muted"><a href="{% url 'password_reset' %}">Forgot Password?</a></small>
                </div>
            </form>

            <!--Register-->
            <div>
                <small class="text-muted mt-2">
                    Need an account? <a href="{% url 'users:users-register' %}">Sign Up</a>
                </small>
            </div>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Logout</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

                <h2>You have been logged out.</h2>
                <h6><a href="{% url 'users:users-login' %}">Login again</a></h6>


        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Reset Password</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Reset Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Your Password Has Been Reset</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">
            <div class="alert alert-info">
                <h1>Your password has been reset</h1>
            </div>
            <h6><a href="{% url 'users:users-login' %}">Login here</a></h6>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Confirm Password Reset</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Reset Password</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Reset Password</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Email Sent</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">
            <div class="alert alert-info">
                <h1>An email has been sent with instructions to reset your password.</h1>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}
<!--LOADING STATIC-->
{% load static %}


<!--CUSTOM STYLESHEET-->
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'users/profile.css' %}">
{% endblock %}

<!--CUSTOM TITLE-->
{% block title %}
    <title>Your Profile</title>
{% endblock %}


<!--CONTENT-->
{% block content %}


<!--PROFILE IMAGE/USER DISPLAY-->
<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">
            <!--Profile image and username-->
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success" role="alert">{{ message|escape|safe }}</div>
                    {% endif %}
            {% endfor %}
            <br>
            <br>
            {% endif %}
        </div>

        <!--DISPLAY IMAGE-->
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-4 mb-100">
            <div class="content-section">
                <div class="media">
                    <img class="img-fluid rounded" src="{{ user.profile.image.url }}">
                </div>
            </div>
            <br>
        </div>

        <!--DISPLAY INTRODUCTION-->
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-8 col-xl-8">
            <div class="media-body">
                <h2 class="account-heading">Welcome {{ user.username }}</h2>
                <p class="text-secondary">You can manage your account and data from our various web applications here.</p>
            </div>
        </div>

    </div>
</div>


<!--WEB APP INFORMATION DISPLAY-->
<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">
            <p class="">View your created events.</p>
            <a href="{% url 'event_management:event_management-events' user.username %}" class="btn btn-primary">View Events</a>
            <br>
            <br>
            <p class="">Add an event.</p>
            <a href="{% url 'event_management:event_management-create' user.username %}" class="btn btn-primary">Add Event</a>
        </div>
    </div>
</div>


<!--UPDATE PROFILE-->
<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">
          <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom">Update your profile</legend>
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Register</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <h1>Register</h1>
            <hr class="red-line">
            <!--Loads the form-->
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <!--Submit button-->
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Sign Up</button>
                </div>
            </form>

            <!--Small text-->
            <small class="text-muted">
                Already have an account? <a href="{% url 'users:users-login' %}">Sign In</a>
            </small>

        </div>
    </div>
</div>

{% endblock %}