event_management/urls.py
from django.urls import path
from .views import (
	EventDetailView, EventListView, EventCreateView, EventUpdateView, EventDeleteView,
	GuestListView, GuestCreateView, GuestUpdateView, GuestDetailView, GuestDeleteView,
	SendEmail, VerifyAttendance, success
)

app_name = 'event_management'
urlpatterns = [
	# EVENTS
	path('<username>/events/', EventListView.as_view(), name='event_management-events'),
	path('<username>/events/new/', EventCreateView.as_view(), name='event_management-create'),
	path('<username>/events/<int:pk>/', EventDetailView.as_view(), name='event_management-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('<username>/events/<int:pk>/update/', EventUpdateView.as_view(), name='event_management-update'),
	path('<username>/events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_management-delete'),

	# GUESTS
	path('<username>/<int:event_pk>/guests/', GuestListView.as_view(), name='guests'),
	path('<username>/<int:event_pk>/guests/new/', GuestCreateView.as_view(), name='guest-create'),
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/', GuestDetailView.as_view(), name='guest-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/update/', GuestUpdateView.as_view(), name='guest-update'),
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/delete/', GuestDeleteView.as_view(), name='guest-delete'),

	# OTHER FUNCTIONALITY
	path('<username>/<int:event_pk>/guests/send-email', SendEmail.as_view(), name='guest-email'),
	path('event-verification/<int:guest_pk>/<str:token>/', VerifyAttendance.as_view(), name='guest-verify'),
	path('event-verification-success/<int:guest_pk>/', success, name='guest-verify-success'),

]

main_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # 'BASIC' PAGES
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('projects/', views.projects, name='projects'),
    path('about/', views.about, name='about'),
    path('', include('users.urls')),


    # TEST ERROR PAGES
    path('400/', views.error_400, name='400'),
    path('403/', views.error_403, name='403'),
    path('404/', views.error_404, name='404'),
    path('500/', views.error_500, name='500'),


    # TESTER PAGES
    path('tester1/', views.tester1, name='tester1'),
    # path('tester2/', views.tester2, name='tester2'),


    # INCLUDING APP URLS
    path('', include('broken_link_checker.urls')),
    path('', include('quizlet_study_tool.urls')),
    path('', include('event_management.urls')),
    path('', include('site_down.urls')),


    # RESET PASSWORD - names must be exact
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

# Overwrites the default error pages
handler400 = 'main_project.views.error_400'
handler403 = 'main_project.views.error_403'
handler404 = 'main_project.views.error_404'
handler500 = 'main_project.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'
urlpatterns = [
	path('register/', user_views.register, name='users-register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
	path('profile/', user_views.profile, name='users-profile'),
]

event_management/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from uuid import uuid4
import datetime

# ADMIN = User.objects.filter(is_superuser=True, username='brickspy').first().pk
BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))


class EventModel(models.Model):
	name = models.CharField(max_length=200, unique=True, null=False, blank=False)
	# If the user gets deleted - remove the events
	author = models.ForeignKey(
		User, on_delete=models.CASCADE, null=False
	)
	date_posted = models.DateTimeField(default=timezone.now)
	date = models.DateTimeField(null=True, blank=True)
	description = models.TextField(max_length=200, null=False, blank=False, default='')

	def __str__(self):
		return self.name

	def date_published(self):
		return self.date.strftime('%m/%d/%Y')

	def get_absolute_url(self):
		return reverse('event_management:event_management-detail', kwargs={'username': self.author, 'pk': self.pk})

	class Meta:
		verbose_name = 'Event'
		verbose_name_plural = 'Events'


class GuestModel(models.Model):
	first_name = models.CharField(max_length=200, null=False, blank=False)
	last_name = models.CharField(max_length=200, blank=True, null=True)
	email = models.EmailField(blank=True, null=True)
	# They click yes after clicking the secret email link
	will_attend = models.BooleanField(blank=True, null=True, default=True, choices=BOOL_CHOICES)
	# , choices = ATTENDANCE_CHOICES
	notes = models.TextField(blank=True, null=True)
	event = models.ForeignKey(EventModel, on_delete=models.CASCADE)
	date_created = models.DateTimeField(default=timezone.now)
	token = models.UUIDField(blank=True, null=True, max_length=100, unique=True)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

	def get_absolute_url(self):
		return reverse('event_management:guest-detail', kwargs={'username': User.username, 'pk': self.pk, 'event_pk': self.event.primary_key})

	def save(self, *args, **kwargs):
		self.token = uuid4().hex
		super().save(*args, **kwargs)

	class Meta:
		verbose_name = 'Guest'
		verbose_name_plural = "Guests"

event_management/forms.py
from django import forms
from .models import EventModel, GuestModel


class EventForm(forms.ModelForm):
	class Meta:
		model = EventModel
		fields = ['name', 'date']
		widgets = {
			'name': forms.TextInput(
				attrs={
					'placeholder': 'Event title',
					'class': 'form-control',
				}),
			'date': forms.DateInput(
				attrs={
					'class': 'form-control',
					'type': 'date',
				}),
			'description': forms.Textarea(
				attrs={
					'placeholder': 'Event description',
					'class': 'form-control',
				}),

		}


TRUE_FALSE_CHOICES = (
	(True, 'Yes'),
	(False, 'No'),
)


class GuestForm(forms.ModelForm):
	class Meta:
		model = GuestModel
		fields = ['will_attend']
		widgets = {
			'will_attend': forms.Select(
				attrs={
					'class': 'form-control',
					'type': 'date',
				},
			),
		}

event_management/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, DeleteView, UpdateView, CreateView, TemplateView
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, send_mass_mail
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site

from .models import EventModel, GuestModel
from .forms import GuestForm, EventForm

"""
***EVENT VIEWS***

"""
class EventListView(LoginRequiredMixin, ListView):
	model = EventModel
	template_name = 'event_management/event_list.html'
	# Default is 'object_list' - this is the context variable
	context_object_name = 'events'
	# Most recent events first
	ordering = ['-date_posted']

	def get_queryset(self):
		return EventModel.objects.filter(author=self.request.user)


class EventDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
	model = EventModel
	template_name = 'event_management/event_detail.html'
	context_object_name = 'event'

	def get_context_data(self, **kwargs):
		# Primary key of event
		pk = self.kwargs['pk']
		# Overrides default get_context_data method?
		context = super(EventDetailView, self).get_context_data(**kwargs)
		# Gets all guest models and names the context 'guestmodel'
		context['guestmodel'] = GuestModel.objects.filter(event=pk)
		return context

	def test_func(self):
		event = EventModel.objects.get(pk=self.kwargs['pk'])
		# Is the current user equal to the author (user that made it)?
		return self.request.user == event.author


# **ADD 'LoginRequiredMixin' TO THE FAR LEFT**
# This is like a login required decorator
class EventCreateView(LoginRequiredMixin, CreateView):
	model = EventModel
	template_name = 'event_management/event_create.html'
	fields = ['name', 'date', 'description']

	# Overrides the form valid method
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


# **ADD 'LoginRequiredMixin' TO THE FAR LEFT**
class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = EventModel
	template_name = 'event_management/event_update.html'
	fields = ['name', 'date', 'description']
	context_object_name = 'events'

	# Overrides the form valid method
	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

	def test_func(self):
		# Gets the current event (model object)
		event = self.get_object()
		# Is the current user equal to the author (user that made it)?
		if self.request.user == event.author:
			return True
		return False


class EventDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = EventModel
	template_name = 'event_management/event_delete.html'

	def get_success_url(self):
		return reverse('event_management:event_management-events', kwargs={'username': self.request.user})

	def test_func(self):
		# Gets the current event (model object)
		event = self.get_object()
		# Is the current user equal to the author (user that made it)?
		if self.request.user == event.author:
			return True
		return False


"""
***GUEST VIEWS***

"""
class GuestListView(LoginRequiredMixin, ListView):
	model = GuestModel
	template_name = 'event_management/guests/guest_list.html'
	# Default is 'object_list' - this is the context variable
	context_object_name = 'guests'
	# Most recent events first
	ordering = ['-date_created']

	def get_queryset(self):
		# All events associated with user
		return GuestModel.objects.filter(event=self.kwargs['event_pk'])

	def get_context_data(self, **kwargs):
		context = super(GuestListView, self).get_context_data(**kwargs)
		event_pk = self.kwargs['event_pk']
		context['event_pk'] = event_pk
		return context


class GuestDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
	model = GuestModel
	template_name = 'event_management/guests/guest_detail.html'
	context_object_name = 'guest'
	pk_url_kwarg = 'guest_pk'

	def test_func(self):
		event = EventModel.objects.get(pk=self.kwargs['event_pk'])
		# Is the current user equal to the author (user that made it)?
		if self.request.user == event.author:
			return True
		return False


# **ADD 'LoginRequiredMixin' TO THE FAR LEFT**
# This is like a login required decorator
class GuestCreateView(LoginRequiredMixin, CreateView):
	model = GuestModel
	template_name = 'event_management/guests/guest_create.html'
	fields = ['first_name', 'last_name', 'email', 'notes']
	context_object_name = 'guest'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		event = EventModel.objects.get(pk=self.kwargs['event_pk'])
		self.object.event = event
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		event_pk = self.kwargs['event_pk']
		return reverse('event_management:guest-create', kwargs={'username': self.request.user, 'event_pk': event_pk})


# **ADD 'LoginRequiredMixin' TO THE FAR LEFT**
class GuestUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = GuestModel
	template_name = 'event_management/guests/guest_update.html'
	fields = ['first_name', 'last_name', 'email', 'notes']
	context_object_name = 'guest'
	# The view looks for 'pk' for the guest model by default
	pk_url_kwarg = 'guest_pk'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		event = EventModel.objects.get(pk=self.kwargs['event_pk'])
		self.object.event = event
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

	def get_success_url(self):
		event_pk = self.kwargs['event_pk']
		guest_pk = self.kwargs['guest_pk']
		return reverse('event_management:guest-detail', kwargs={'username': self.request.user, 'event_pk': event_pk, 'guest_pk': guest_pk})

	def test_func(self):
		event = EventModel.objects.get(pk=self.kwargs['event_pk'])
		if self.request.user == event.author:
			return True
		return False


class GuestDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = GuestModel
	template_name = 'event_management/guests/guest_delete.html'
	context_object_name = 'guest'
	pk_url_kwarg = 'guest_pk'

	def get_success_url(self):
		event_pk = self.kwargs['event_pk']
		return reverse('event_management:guests', kwargs={'username': self.request.user, 'event_pk': event_pk})

	def test_func(self):
		event = EventModel.objects.get(pk=self.kwargs['event_pk'])
		if self.request.user == event.author:
			return True
		return False


class SendEmail(TemplateView):
	def get(self, request, *args, **kwargs):
		# Event primary key
		event_pk = self.kwargs['event_pk']
		# Get guests with that pk
		guest_objects = GuestModel.objects.filter(event=event_pk, will_attend=True)
		# Get the guest emails
		# [[email, token, pk], [email, token, pk]]
		guests = [[guest.email, guest.token, guest.pk, guest.first_name] for guest in guest_objects]
		# The event
		event = EventModel.objects.get(pk=event_pk)

		# send_email params
		for guest in guests:
			subject = f'{guest[3]}, you are invited'
			token_url = reverse('event_management:guest-verify', kwargs={'guest_pk': guest[2], 'token': guest[1]})
			token_url = str(get_current_site(request=request)) + token_url
			message = f'You are invited to {event}.\nTo verify your attendance, ' \
					  f'click the link: {token_url}'
			from_email = settings.EMAIL_HOST_USER
			recipient_list = [guest[0]]
			auth_user = settings.EMAIL_HOST_USER
			auth_password = settings.EMAIL_HOST_PASSWORD
			datatuple = (subject, message, from_email, recipient_list)
			send_mass_mail(
				datatuple=(datatuple,), fail_silently=True, auth_user=auth_user, auth_password=auth_password,
			)

		context = {
			'guests': guest_objects,
			'event': event,
		}

		return render(request, 'event_management/functionality/send_email.html', context)


class VerifyAttendance(UpdateView):
	model = GuestModel
	template_name = 'event_management/functionality/attend_event.html'
	fields = ['will_attend']
	context_object_name = 'guest'
	pk_url_kwarg = 'guest_pk'

	def get_success_url(self):
		return reverse('event_management:guest-verify-success', kwargs={'guest_pk': self.kwargs['guest_pk']})


def success(request, guest_pk):
	template_name = 'event_management/functionality/attend_event_success.html'
	context = {

	}

	return render(request, template_name, context)

event_management/templates/event_management/event_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Create Event</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Label-->
            <h1>Create the event</h1>
            <hr class="red-line">

            <!--The form-->
            <form method="POST">
                {% csrf_token %}
                {{ form.name|as_crispy_field }}
                <p>Format as: 01/01/2000</p>
                {{ form.date|as_crispy_field }}
                {{ form.description|as_crispy_field }}

                <!--Submit-->
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Create</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

event_management/templates/event_management/event_delete.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}

<!--CUSTOM TITLE-->
{% block title %}
    <title>Delete Event</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Label-->
            <h1>Delete the event</h1>
            <hr class="red-line">

            <!--Form-->
            <form method="POST">
                {% csrf_token %}
                <h3>Confirm "{{ object.name }}" deletion</h3>
                <br>

                <!--Delete, cancel buttons-->
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Delete</button>
                    <a class="btn btn-outline-secondary" href="{% url 'event_management:event_management-detail' user.username object.id %}">Cancel</a>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}

event_management/templates/event_management/event_detail.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS STATIC FILES-->
{% load static %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Your Event</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Event details-->
            <h1>Event: {{ event }}</h1>
            <h4>Event Date: {{ event.date_published }}</h4>
            <h6>Date posted: {{ event.date_posted }}</h6>
            <p>Event description: {{ event.description }}</p>
            <br>

            <!--Delete, update event-->
            <div>
                <a class="btn btn-outline-success" href="{% url 'event_management:event_management-update' user.username event.id %}">Update event</a>
            </div>

            <br>

            <div>
                <a class="btn btn-outline-danger" href="{% url 'event_management:event_management-delete' user.username event.id %}">Delete event</a>
            </div>

            <br>

            <!--Guests-->
            <div>
                <h5>"{{ event }}" guests</h5>
                <a class="btn btn-primary" href="{% url 'event_management:guests' user.username event.id %}">Guests</a>
            </div>
            <br>

            <!--Events-->
            <h5>All of your events</h5>
            <a class="btn btn-primary" href="{% url 'event_management:event_management-events' user.username %}">All Events</a>

        </div>
    </div>
</div>

{% endblock %}

event_management/templates/event_management/event_list.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS STATIC FILES-->
{% load static %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Your Events</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Are there any events?-->
            {% if not events %}
                <h1>You have not created any events.</h1>
                <br>
            {% endif %}

            <!--Text-->
            {% if events %}
                <h1>These are all of your events</h1>
                <br>
            {% endif %}

            <!--Create an event-->
            <a class="btn btn-primary" href="{% url 'event_management:event_management-create' user.username %}">Create an event</a>
            <br>
            <br>

            <!--Event list-->
            {% for event in events %}
                <h5><a href="{% url 'event_management:event_management-detail' user.username event.id %}">{{ event.name }}</a></h5>
                <br>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

event_management/templates/event_management/event_update.html
<!--EXTENDS FROM BASE-->
{% extends 'base.html' %}
<!--LOADS CRISPY FORM TAGS-->
{% load crispy_forms_tags %}


<!--CUSTOM TITLE-->
{% block title %}
    <title>Update Event</title>
{% endblock %}


<!--CONTENT-->
{% block content %}

<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">

            <!--Label-->
            <h1>Update the event</h1>
            <hr class="red-line">

            <!--Form-->
            <form method="POST">
                {% csrf_token %}
                {{ form.name|as_crispy_field }}
                <p>Format as: 01/01/2000</p>
                {{ form.date|as_crispy_field }}
                {{ form.description|as_crispy_field }}

                <!--Submit-->
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Submit</button>
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock %}