broken_link_checker/urls.py
from django.urls import path
from .views import broken_link_checker

app_name = 'broken_link_checker'
urlpatterns = [
	path('broken-link-checker/', broken_link_checker, name='broken-link-checker'),

]

event_management/urls.py
from django.urls import path
from .views import (
	EventDetailView, EventListView, EventCreateView, EventUpdateView, EventDeleteView,
	GuestListView, GuestCreateView, GuestUpdateView, GuestDetailView, GuestDeleteView,
	SendEmail, VerifyAttendance, success
)

app_name = 'event_management'
urlpatterns = [
	# EVENTS
	path('<username>/events/', EventListView.as_view(), name='event_management-events'),
	path('<username>/events/new/', EventCreateView.as_view(), name='event_management-create'),
	path('<username>/events/<int:pk>/', EventDetailView.as_view(), name='event_management-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('<username>/events/<int:pk>/update/', EventUpdateView.as_view(), name='event_management-update'),
	path('<username>/events/<int:pk>/delete/', EventDeleteView.as_view(), name='event_management-delete'),

	# GUESTS
	path('<username>/<int:event_pk>/guests/', GuestListView.as_view(), name='guests'),
	path('<username>/<int:event_pk>/guests/new/', GuestCreateView.as_view(), name='guest-create'),
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/', GuestDetailView.as_view(), name='guest-detail'),
	# Leave 'update' at the end - the user may have an event called 'update'
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/update/', GuestUpdateView.as_view(), name='guest-update'),
	path('<username>/<int:event_pk>/guest/<int:guest_pk>/delete/', GuestDeleteView.as_view(), name='guest-delete'),

	# OTHER FUNCTIONALITY
	path('<username>/<int:event_pk>/guests/send-email', SendEmail.as_view(), name='guest-email'),
	path('event-verification/<int:guest_pk>/<str:token>/', VerifyAttendance.as_view(), name='guest-verify'),
	path('event-verification-success/<int:guest_pk>/', success, name='guest-verify-success'),

]

main_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # 'BASIC' PAGES
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('projects/', views.projects, name='projects'),
    path('about/', views.about, name='about'),
    path('', include('users.urls')),


    # TEST ERROR PAGES
    path('400/', views.error_400, name='400'),
    path('403/', views.error_403, name='403'),
    path('404/', views.error_404, name='404'),
    path('500/', views.error_500, name='500'),


    # TESTER PAGES
    path('tester1/', views.tester1, name='tester1'),
    # path('tester2/', views.tester2, name='tester2'),


    # INCLUDING APP URLS
    path('', include('broken_link_checker.urls')),
    path('', include('quizlet_study_tool.urls')),
    path('', include('event_management.urls')),
    path('', include('site_down.urls')),


    # RESET PASSWORD - names must be exact
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

# Overwrites the default error pages
handler400 = 'main_project.views.error_400'
handler403 = 'main_project.views.error_403'
handler404 = 'main_project.views.error_404'
handler500 = 'main_project.views.error_500'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizlet_study_tool/urls.py
from django.urls import path
from .views import quizlet_answer

app_name = 'quizlet_study_tool'
urlpatterns = [
	path('quizlet-answer/', quizlet_answer, name='quizlet-answer'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views as user_views

app_name = 'users'
urlpatterns = [
	path('register/', user_views.register, name='users-register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
	path('profile/', user_views.profile, name='users-profile'),
]

templates/components/capstone_projects.html
<!--LOADING THE STYLESHEET-->
{% load static %}
<link rel="stylesheet" href="{% static 'components_stylesheets/capstone_projects.css' %}">


<!--CAPSTONE PROJECTS-->
<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col 12">
            <h1 class="display-4">My Capstone Projects</h1>
        </div>
    </div>
    <hr class="red-line">
</div>


<!-- CAPSTONE PROJECTS CARDS-->
<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="card">
                <!--top = image at the top, middle = image in middle, bottom... etc-->
                <img class="card-img-top" src="{% static 'images/project_pictures/broken_link.png' %}" width="300" height="210" alt="...">
                <div class="card-body">
                    <h4 class="card-title"><strong>Broken Link Checker</strong></h4>
                    <p class="card-text">Finds all the broken links on a page.</p>
                    <br>
                    <a href="{% url 'broken_link_checker:broken-link-checker' %}" class="btn btn-primary">See Project</a>
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="card">
                <!--top = image at the top, middle = image in middle, bottom... etc-->
                <img class="card-img-top" src="{% static 'images/project_pictures/event.png' %}" width="300" height="210" alt="...">
                <div class="card-body">
                    <h4 class="card-title"><strong>Event Manager</strong></h4>
                    <p class="card-text">Send event invites, track who is going.</p>
                    <br>
                    {% if user.is_authenticated %}
                        <a href="{% url 'event_management:event_management-events' user.username %}" class="btn btn-primary">See Project</a>
                    {% else %}
                        <a href="{% url 'users:users-login' %}" class="btn btn-primary">Login/Register To View</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="card">
                <!--top = image at the top, middle = image in middle, bottom... etc-->
                <img class="card-img-top" src="{% static 'images/project_pictures/quizlet.png' %}" width="300" height="210" alt="...">
                <div class="card-body">
                    <h4 class="card-title"><strong>Quizlet Study Tool</strong></h4>
                    <p class="card-text">Finds the answer to a question using Quizlet.</p>
                    <a href="{% url 'quizlet_study_tool:quizlet-answer' %}" class="btn btn-primary">See Project</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/footer.html
<!--LOADING THE STYLESHEET-->
{% load static %}
<link rel="stylesheet" href="{% static 'components_stylesheets/footer.css' %}">

<!--THE FOOTER-->
<div class="navbar-static-bottom" id="footer">
    <footer>
        <div class="container text-center">
            <hr class="light">
            <h5>about | contact | &copy; nathanemartinez.com</h5>
        </div>
    </footer>
</div>

templates/components/navbar.html
<!--LOADING THE STYLESHEET-->
{% load static %}
<link rel="stylesheet" href="{% static 'components_stylesheets/navbar.css' %}">

<!--THE NAVBAR-->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark" id="main-navbar">
  <!--Main navbar link-->
  <a class="navbar-brand" id="navbar-brand" href="/">Nathan Martinez</a>

  <!--Toggle switch-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!--Links-->
  <div class="navbar-collapse collapse justify-content-end" id="navbarSupportedContent">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item" id="projects-nav-item">
        <a class="nav-link" id="projects-nav-link" href="{% url 'projects' %}">Projects</a>
      </li>
      <li class="nav-item" id="about-nav-item">
        <a class="nav-link" id="about-nav-link" href="{% url 'about' %}">About</a>
      </li>

      {% if user.is_authenticated %}
        <li class="nav-item" id="profile-nav-item">
          <a class="nav-link" id="profile-nav-link" href="{% url 'users:users-profile' %}">Profile</a>
        </li>
        <li class="nav-item" id="logout-nav-item">
          <a class="nav-link" id="logout-nav-link" href="{% url 'users:users-logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item" id="login-nav-item">
          <a class="nav-link" id="login-nav-link" href="{% url 'users:users-login' %}">Login</a>
        </li>
        <li class="nav-item" id="register-nav-item">
          <a class="nav-link" id="register-nav-link" href="{% url 'users:users-register' %}">Register</a>
        </li>
      {% endif %}

    </ul>
  </div>
</nav>

templates/components/skills.html
<!--LINKING THE STYLESHEET-->
{% load static %}
<link rel="stylesheet" href="{% static 'components_stylesheets/skills.css' %}">

<!--"MY SKILLS"-->
<div class="container-fluid padding">
	<div class="row text-center welcome">
		<div class="col-12">
			<h1 class="display-4">My Skills</h1>
		</div>
		<div class="col-12">
			<p class="lead">What I've learned.</p>
		</div>
	</div>
	<hr class="red-line">
</div>


<!--MY SKILLS LIST-->
<div class="container-fluid padding">
	<div class="row text-center padding">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<i class="fas fa-graduation-cap fa-6x"></i>
			<h3><strong>Machine Learning</strong></h3>
			<p>I can develop machine learning models that can predict values.
				I used the Census Dataset to predict how much money someone made a year.
			</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<i class="fab fa-python fa-6x"></i>
			<h3><strong>Web Application Development</strong></h3>
			<p>I have designed, tested, and deployed web applications that have full CRUD (create, read, update, delete) functionality.</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<i class="fas fa-language fa-6x"></i>
			<h3><strong>Natural Language Processing</strong></h3>
			<p>I've used NLP in several of my projects to remove 'stopwords' and 'lemmatize' text.</p>
		</div>
	</div>
</div>

templates/components/socials.html
<!--LOADING THE STYLESHEET-->
{% load static %}
<link rel="stylesheet" href="{% static 'components_stylesheets/socials.css' %}">


<!--THE SOCIALS-->
<div class="container-fluid padding">
    <div class="row text-center welcome">
        <div class="col-12">
            <h1 class="display-4">Connect with me</h1>
        </div>
        <hr class="red-line">
        <div class="col-12 social padding">
                <a href="https://www.linkedin.com/in/nathanemartinez/" target="_blank"><i class="fab fa-linkedin fa-4x"></i></a>
                <a href="https://github.com/nathanemartinez" target="_blank"><i class="fab fa-github fa-4x"></i></a>
        </div>
    </div>
</div>